apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-customers-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lanchonete-customers-api
  template:
    metadata:
      labels:
        app: lanchonete-customers-api
    spec:
      containers:
        - name: lanchonete-customers-api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DB_USER
              value: {{ .Values.api.env.DB_USER }}
            - name: DB_PASSWORD
              value: {{ .Values.api.env.DB_PASSWORD }}
            - name: DB_NAME
              value: {{ .Values.api.env.DB_NAME }}
            - name: DB_HOST
              value: {{ .Values.api.env.DB_HOST }}
            - name: DB_PORT
              value: "{{ .Values.api.env.DB_PORT }}"
            - name: PORT
              value: "{{ .Values.api.env.PORT }}"
